
class PsValueHolder {
  PsValueHolder(
      {required this.loginUserId,
      required this.loginUserName,
      required this.locationId,
      required this.locactionName,
      required this.locationLat,
      required this.locationLng,
      required this.locationTownshipId,
      required this.locationTownshipName,
      required this.locationTownshipLat,
      required this.locationTownshipLng,
      required this.userIdToVerify,
      required this.userNameToVerify,
      required this.userEmailToVerify,
      required this.userPasswordToVerify,
      required this.deviceToken,
      required this.notiSetting,
      required this.isCustomCamera,
      required this.isToShowIntroSlider,
      required this.overAllTaxLabel,
      required this.overAllTaxValue,
      required this.shippingTaxLabel,
      required this.shopId,
      required this.messenger,
      required this.whatsApp,
      required this.phone,
      required this.shippingTaxValue,
      required this.appInfoVersionNo,
      required this.appInfoForceUpdate,
      required this.appInfoForceUpdateTitle,
      required this.appInfoForceUpdateMsg,
      required this.startDate,
      required this.endDate,
      required this.paypalEnabled,
      required this.stripeEnabled,
      required this.codEnabled,
      required this.bankEnabled,
      required this.publishKey,
      required this.shippingId,
      required this.standardShippingEnable,
      required this.zoneShippingEnable,
      required this.noShippingEnable,
      required this.isSubLocation,
      required this.isThumbnail2x3xGenerate,
      required this.defaultCurrency,
      required this.defaultCurrencyId,
      required this.detailOpenCount,
      required this.blockedFeatureDisabled,
      required this.isPaidApp,
      required this.isModelSubScribe,
      required this.maxImageCount,
      required this.adType,
      required this.promoCellNo,
      required this.itemType,
      required this.priceType,
      required this.condition,
      required this.video,
      required this.discountRate,
      required this.businessMode,
      required this.highlightInfo,
      required this.color, 
      required this.fuelType, 
      required this.buildType, 
      required this.sellerType, 
      required this.transmissionId,
      required this.plateNumber, 
      required this.enginePower, 
      required this.steeringPosition, 
      required this.noOfOwner, 
      required this.trimName, 
      required this.vehicleId,
      required this.priceUnit, 
      required this.year, 
      required this.licenceStatus, 
      required this.maxPassengers, 
      required this.noOfDoors, 
      required this.mileage, 
      required this.licenceExpirationDate, 
      required this.address,

      required this.googlePlayStoreUrl,
      required this.appleAppStoreUrl,
      required this.priceFormat,
      required this.dateFormat,
      required this.iosAppStoreId,
      required this.isUseThumbnailAsPlaceHolder,
      required this.isShowTokenId,
      required this.isShowSubcategory,
      required this.fbKey,
      required this.isShowAdmob,
      required this.defaultLoadingLimit,
      required this.categoryLoadingLimit,
      required this.recentItemLoadingLimit,
      required this.populartItemLoadingLimit,
      required this.discountItemLoadingLimit,
      required this.featuredItemLoadingLimit,
      required this.blockSliderLoadingLimit,
      required this.followerItemLoadingLimit,
      required this.blockItemLoadingLimit,
      required this.showFacebookLogin,
      required this.showGoogleLogin,
      required this.showPhoneLogin,
      required this.isRazorSupportMultiCurrency,
      required this.defaultRazorCurrency,
      required this.itemDetailViewCountForAds,
      required this.isShowAdsInItemDetail,
      required this.isShowAdmobInsideList,
      required this.bluemarkSize,
      required this.mile,
      required this.videoDuration,
      required this.isUseGoogleMap,
      required this.profileImageSize,
      required this.uploadImageSize,
      required this.chatImageSize,
      required this.promoteFirstChoiceDay,
      required this.promoteSecondChoiceDay,
      required this.promoteThirdChoiceDay,
      required this.promoteFourthChoiceDay,
      required this.noFilterWithLocationOnMap,
      required this.isShowOwnerInfo,
      required this.defaultLanguageCode,
      required this.packageAndroidKeyList,
      required this.packageIOSKeyList,
      required this.isForceLogin,
      required this.isLanguageConfig,
      });
  String? locationId;
  String? locactionName;
  String? locationLat;
  String? locationLng;
  String locationTownshipId;
  String locationTownshipName;
  String locationTownshipLat;
  String locationTownshipLng;
  String? loginUserId;
  String? loginUserName;
  String? userIdToVerify;
  String? userNameToVerify;
  String? userEmailToVerify;
  String? userPasswordToVerify;
  String? deviceToken;
  bool? notiSetting;
  bool isCustomCamera;
  bool isToShowIntroSlider;
  String? overAllTaxLabel;
  String? overAllTaxValue;
  String? shippingTaxLabel;
  String? shopId;
  String? messenger;
  String? whatsApp;
  String? phone;
  String? shippingTaxValue;
  String? appInfoVersionNo;
  bool? appInfoForceUpdate;
  String? appInfoForceUpdateTitle;
  String? appInfoForceUpdateMsg;
  String? startDate;
  String? endDate;
  String? paypalEnabled;
  String? stripeEnabled;
  String? codEnabled;
  String? bankEnabled;
  String? publishKey;
  String? shippingId;
  String? standardShippingEnable;
  String? zoneShippingEnable;
  String? noShippingEnable;
  String isSubLocation;
  String isThumbnail2x3xGenerate;
  String defaultCurrency;
  String defaultCurrencyId;
  int? detailOpenCount;

  String? blockedFeatureDisabled;
  String? isPaidApp;
  String? isModelSubScribe;
  int maxImageCount;
  String? adType;
  String? promoCellNo;

  //item upload config
  String? itemType, priceType, condition, video, discountRate, businessMode, highlightInfo, color, fuelType,
   buildType, sellerType, transmissionId, plateNumber, enginePower, steeringPosition, noOfOwner, trimName,
   vehicleId, priceUnit, year, licenceStatus, maxPassengers, noOfDoors, mileage, licenceExpirationDate, 
   address;

   //Mobile Config
  String? googlePlayStoreUrl;
  String? appleAppStoreUrl;
  String? priceFormat;
  String? dateFormat;
  String? iosAppStoreId;
  bool? isUseThumbnailAsPlaceHolder;
  bool? isShowTokenId;
  bool? isShowSubcategory;
  String? fbKey;
  bool? isShowAdmob;
  int? defaultLoadingLimit;
  int? categoryLoadingLimit;
  int? recentItemLoadingLimit;
  int? populartItemLoadingLimit;
  int? discountItemLoadingLimit;
  int? featuredItemLoadingLimit;
  int? blockSliderLoadingLimit;
  int? followerItemLoadingLimit;
  int? blockItemLoadingLimit;
  bool? showFacebookLogin;
  bool? showGoogleLogin;
  bool? showPhoneLogin;
  bool? isRazorSupportMultiCurrency;
  String? defaultRazorCurrency;
  int? itemDetailViewCountForAds;
  bool? isShowAdsInItemDetail;
  bool? isShowAdmobInsideList;
  double? bluemarkSize;
  String? mile;
  String? videoDuration;
  bool? isUseGoogleMap;
  int? profileImageSize;
  int? uploadImageSize;
  int? chatImageSize;
  String? promoteFirstChoiceDay;
  String? promoteSecondChoiceDay;
  String? promoteThirdChoiceDay;
  String? promoteFourthChoiceDay;
  bool? noFilterWithLocationOnMap;
  bool? isShowOwnerInfo;
  String? defaultLanguageCode;
  String? packageAndroidKeyList;
  String? packageIOSKeyList;
  bool? isForceLogin;
  bool? isLanguageConfig;
}

